before_install:
- gem install compass
- npm install -g bower
- npm install -g grunt-cli
- npm install -g protractor
install:
- npm install -d
- bower install
- webdriver-manager update
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- curl https://gist.github.com/santiycr/5139565/raw/sauce_connect_setup.sh | bash
language: node_js
node_js:
- '0.8'
- '0.10'
env:
  global:
  - secure: XNGijrA8aJI4BYcNGgWY1+337H8OosFOaV/QFSO27ZiPAM2hEM6IL1tgL+kHNCepiOwfTdpwpLKgDBV8uwu0FIIF1k0La8pJ32XCJw6WENZ4iwUiuEsCgiZIC4TJENFqlELxK+9RLb6lr9XcqnFLlBm21h78oU6iocp7RCIQZWs=
  - secure: M3/9SqZyU+UjcLp73+DfrFPpISjnQ1JjawXfwZ6t52RlOQ2uCYG0uDvod9ydrxZ+2MZ6mM1IIZtS4MLu73jrURE7leMbGk8G1P9P1tY/EVTt+YA4ySrVflkPePrZ4XOvSJRow/0o1xr12Fwy3J2psRpssSEc0omi3azhQ2N3ybA=
